#!/bin/bash

printenv

read -r -d '' PACKAGES << EOM #Packages to install
acpi
acpid
build-essential
curl
fonts-dejavu
fonts-dejavu-core
fonts-dejavu-extra
fonts-inconsolata
fonts-vlgothic
git
i3
rxvt-unicode-256color
strace
sudo
ttf-dejavu
ttf-dejavu-core
ttf-dejavu-extra
vim-nox
xorg
xclip
feh
compton
tmux
xbindkeys
EOM

sudo apt-get update && echo $PACKAGES | xargs sudo -E apt-get install -y

curl -sSL https://get.docker.com/ | sudo sh

sudo adduser $USER docker

DEVPATH=$HOME/dev
BINPATH=$HOME/bin
TOOLSPATH=$HOME/tools
mkdir -p $DEVPATH $BINPATH $TOOLSPATH

git clone https://github.com/netbrain/dotfiles $DEVPATH/dotfiles && cd $DEVPATH/dotfiles && make
